#!/usr/bin/env bash
set -euo pipefail

version="${1:?usage: update-channels.sh <version> <dist-dir> [tap-checkout]}"
dist="${2:?}"
tap="${3:-}"
repo="${CRABBOX_CLI_REPO:-gperezmz/crabbox-cli}"
base="https://github.com/$repo/releases/download/v$version"

sha() { awk -v f="./crabbox_${version}_$1.$2" '$2 == f { print $1 }' "$dist/checksums.txt"; }

nix_asset() {
  printf '    "%s": { "url": "%s/crabbox_%s_%s.tar.gz", "sha256": "%s" }' \
    "$1" "$base" "$version" "$2" "$(sha "$2" tar.gz)"
}

{
  printf '{\n  "version": "%s",\n  "assets": {\n' "$version"
  nix_asset aarch64-darwin darwin_arm64; printf ',\n'
  nix_asset x86_64-darwin darwin_amd64; printf ',\n'
  nix_asset aarch64-linux linux_arm64; printf ',\n'
  nix_asset x86_64-linux linux_amd64; printf '\n  }\n}\n'
} >release.json

[ -n "$tap" ] || exit 0

mkdir -p "$tap/Formula"
cat >"$tap/Formula/crabbox.rb" <<RUBY
# Generated by $repo. Do not edit by hand.
class Crabbox < Formula
  desc "Crabbox CLI built from gperezmz/crabbox (GCP capabilities)"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/crabbox_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64 tar.gz)"
    end
    on_intel do
      url "$base/crabbox_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64 tar.gz)"
    end
  end

  on_linux do
    on_arm do
      url "$base/crabbox_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64 tar.gz)"
    end
    on_intel do
      url "$base/crabbox_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64 tar.gz)"
    end
  end

  def install
    bin.install "crabbox"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crabbox version")
  end
end
RUBY
